AWSTemplateFormatVersion: 2010-09-09
Description: Consumer VPC, VPC Lattice (service network and resource associations), and EC2 Instances
Transform: 'AWS::LanguageExtensions'

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
  ssmResourceConfiguration:
    Type: String
    Description: Resource Configuration for ssm endpoint
  ssmmessagesResourceConfiguration:
    Type: String
    Description: Resource Configuration for ssmmessages endpoint
  ec2messagesResourceConfiguration:
    Type: String
    Description: Resource Configuration for ec2messages endpoint
  stsResourceConfiguration:
    Type: String
    Description: Resource Configuration for sts endpoint

Mappings:
  SubnetToIndex:
    Workloada:
      Index: 0
    Workloadb:
      Index: 1

Resources:
  # ---------- VPC ----------
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Join
            - '-'
            - - consumer-vpc
              - !Ref AWS::StackName

  Ipv6Cidr:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

  # For::Each iteration: per AZ (2 AZs)
  # Resources to create: 2 subnets, 2 route tables, 2 route table associations - obtaining AZ affinity
  'Fn::ForEach::AZ':
    - AvailabilityZone
    - [a, b]
    - 'WorkloadSubnet${AvailabilityZone}':
        DependsOn:
          - Ipv6Cidr
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Sub ${AWS::Region}${AvailabilityZone}
          CidrBlock: !Select 
            - !FindInMap [SubnetToIndex, !Sub "Workload${AvailabilityZone}", Index]
            - !Cidr 
              - !GetAtt VPC.CidrBlock
              - 256
              - 8
          Ipv6CidrBlock: !Select 
            - !FindInMap [SubnetToIndex, !Sub "Workload${AvailabilityZone}", Index]
            - !Cidr 
              - !Select [0, !GetAtt VPC.Ipv6CidrBlocks]
              - 256
              - 64
          AssignIpv6AddressOnCreation: true
          Tags:
            - Key: Name
              Value: !Join
                - '-'
                - - !Sub consumer-subnet-workload-AZ${AvailabilityZone}
                  - !Ref AWS::StackName
      # Route Tables
      'WorkloadRouteTable${AvailabilityZone}':
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId: !Ref VPC
          Tags: 
            - Key: Name
              Value: !Join
                - '-'
                - - !Sub consumer-rt-workload-AZ${AvailabilityZone}
                  - !Ref AWS::StackName
      # Route Table associations
      'WorkloadRouteTableAssociation${AvailabilityZone}':
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties: 
          RouteTableId: !Ref
            'Fn::Sub': 'WorkloadRouteTable${AvailabilityZone}'
          SubnetId: !Ref
            'Fn::Sub': 'WorkloadSubnet${AvailabilityZone}'
  
  # Security Group (Instances)
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Instance Security Group
      VpcId: !Ref VPC
  
  InstanceSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      Description: Allowing egress traffic (IPv4)
      IpProtocol: -1
      CidrIp: 0.0.0.0/0
  
  InstanceSecurityGroupEgressIPv6:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      Description: Allowing egress traffic (IPv6)
      IpProtocol: -1
      CidrIpv6: ::/0

  # Security Group (VPC Lattice VPC association)
  VpcLatticeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC Lattice VPC association Security Group
      VpcId: !Ref VPC
  
  VpcLatticeSecurityGroupIngressInstanceHTTPS:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref VpcLatticeSecurityGroup
      Description: Allowing HTTPS traffic
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref InstanceSecurityGroup
  
  # ---------- VPC LATTICE SERVICE NETWORK AND ASSOCIATIONS ----------
  # VPC Lattice Service Network
  VpcLatticeServiceNetwork:
    Type: AWS::VpcLattice::ServiceNetwork
    Properties:
      AuthType: NONE
      Name: service-network

  # VPC Lattice service network VPC association
  VpcLatticeVpcAssociation:
    Type: AWS::VpcLattice::ServiceNetworkVpcAssociation
    Properties:
      DnsOptions: 
          PrivateDnsPreference: SPECIFIED_DOMAINS_ONLY
          PrivateDnsSpecifiedDomains: 
            - '*.amazonaws.com'
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref VpcLatticeSecurityGroup
      ServiceNetworkIdentifier: !Ref VpcLatticeServiceNetwork
      VpcIdentifier: !Ref VPC

  # For::Each iteration: per VPC endpoint type (ssm, ssmmessages, ec2messages, sts)
  # Resources to create: 4 Resource Configuration associations
  'Fn::ForEach::EndpointTypes':
    - EndpointType
    - [ssm, ssmmessages, ec2messages, sts]
    - '${EndpointType}ResourceAssociation':
        Type: AWS::VpcLattice::ServiceNetworkResourceAssociation
        Properties:
          PrivateDnsEnabled: true
          ResourceConfigurationId: !Ref
            'Fn::Sub': '${EndpointType}ResourceConfiguration'
          ServiceNetworkId: !Ref VpcLatticeServiceNetwork

  # ---------- IAM ROLE (EC2 INSTANCE) ----------
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ec2_ssm_role_${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: '1'
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'ec2_instance_profile_${AWS::StackName}'
      Roles:
        - !Ref EC2InstanceRole

  # ---------- EC2 INSTANCES ----------
  # For::Each iteration: per AZ (2 AZs)
  'Fn::ForEach::Instances':
    - AvailabilityZone
    - [a, b]
    - 'Instance${AvailabilityZone}':
        Type: AWS::EC2::Instance
        Properties:
          InstanceType: t3.micro
          SecurityGroupIds:
            - !Ref InstanceSecurityGroup
          SubnetId: !Ref 
            'Fn::Sub': 'WorkloadSubnet${AvailabilityZone}'
          ImageId: !Ref LatestAmiId
          Ipv6AddressCount: 1
          IamInstanceProfile: !Ref EC2InstanceProfile
          MetadataOptions:
            HttpEndpoint: enabled
            HttpTokens: required
          BlockDeviceMappings:
            - DeviceName: /dev/xvda
              Ebs:
                Encrypted: true
          Tags:
            - Key: Name
              Value: !Join
                - '-'
                - - !Sub consumer-instance-${AvailabilityZone}
                  - !Ref AWS::StackName
  
Outputs:  
  InstanceA:
    Description: Consumer EC2 Instance ID (AZ a)
    Value: !Ref Instancea
  InstanceB:
    Description: Consumer EC2 Instance ID (AZ b)
    Value: !Ref Instanceb