AWSTemplateFormatVersion: 2010-09-09
Description: Central VPC endpoints VPC
Transform: 'AWS::LanguageExtensions'

Mappings:
  SubnetToIndex:
    RGWa:
      Index: 0
    RGWb:
      Index: 1
    Endpointsa:
      Index: 2
    Endpointsb:
      Index: 3

Resources:
  # ---------- VPC ----------
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags: 
        - Key: Name
          Value: !Join
            - '-'
            - - endpoints-vpc
              - !Ref AWS::StackName

  Ipv6Cidr:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

  # For::Each iteration: per subnet type (RGW, Endpoints) and AZ (2 AZs)
  # Resources to create: 4 subnets, 4 route tables, 4 route table associations - obtaining AZ affinity
  'Fn::ForEach::SubnetTypes':
    - SubnetType
    - [RGW, Endpoints]
    - '${SubnetType}':
      'Fn::ForEach::AZ':
        - AvailabilityZone
        - [a, b]
          # Subnets
        - '${SubnetType}Subnet${AvailabilityZone}':
            DependsOn:
              - Ipv6Cidr
            Type: AWS::EC2::Subnet
            Properties:
              VpcId: !Ref VPC
              AvailabilityZone: !Sub ${AWS::Region}${AvailabilityZone}
              CidrBlock: !Select 
                - !FindInMap [SubnetToIndex, !Sub "${SubnetType}${AvailabilityZone}", Index]
                - !Cidr 
                  - !GetAtt VPC.CidrBlock
                  - 256
                  - 8
              Ipv6CidrBlock: !Select 
                - !FindInMap [SubnetToIndex, !Sub "${SubnetType}${AvailabilityZone}", Index]
                - !Cidr 
                  - !Select [0, !GetAtt VPC.Ipv6CidrBlocks]
                  - 256
                  - 64
              AssignIpv6AddressOnCreation: true
              Tags:
                - Key: Name
                  Value: !Join
                    - '-'
                    - - !Sub consumer-subnet-${SubnetType}-AZ${AvailabilityZone}
                      - !Ref AWS::StackName
          # Route Tables
          '${SubnetType}RouteTable${AvailabilityZone}':
            Type: AWS::EC2::RouteTable
            Properties:
              VpcId: !Ref VPC
              Tags: 
                - Key: Name
                  Value: !Join
                    - '-'
                    - - !Sub consumer-rt-${SubnetType}-AZ${AvailabilityZone}
                      - !Ref AWS::StackName
          # Route Table associations
          '${SubnetType}RouteTableAssociation${AvailabilityZone}':
            Type: AWS::EC2::SubnetRouteTableAssociation
            Properties: 
              RouteTableId: !Ref
                'Fn::Sub': '${SubnetType}RouteTable${AvailabilityZone}'
              SubnetId: !Ref
                'Fn::Sub': '${SubnetType}Subnet${AvailabilityZone}'
  
  # Security Group (Resource Gateway)
  RGWSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Resource Gateway Security Group
      VpcId: !Ref VPC
  
  RGWSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref RGWSecurityGroup
      Description: Allowing TCP egress traffic (local VPC)
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrIp: 10.0.0.0/16

  # Security Group (VPC endpoints)
  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPC Endpoints Security Group
      VpcId: !Ref VPC
  
  EndpointSecurityGroupIngressRGW:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EndpointSecurityGroup
      Description: Allowing HTTPS traffic from Resource Gateway
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref RGWSecurityGroup

  EndpointSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref EndpointSecurityGroup
      Description: Allowing egress traffic (any within local VPC)
      IpProtocol: "-1"
      CidrIp: 10.0.0.0/16
  
  # ---------- RESOURCE GATEWAY ----------
  ResourceGateway:
    Type: AWS::VpcLattice::ResourceGateway
    Properties:
      IpAddressType: DUALSTACK
      Name: resource-gateay
      SecurityGroupIds: 
        - !Ref RGWSecurityGroup
      SubnetIds: 
        - !Ref RGWSubneta
        - !Ref RGWSubnetb
      VpcIdentifier: !Ref VPC

  # ---------- VPC ENDPOINTS & RESOURCE CONFIGURATIONS ----------
  # For::Each iteration: per VPC endpoint type (ssm, ssmmessages, ec2messages, sts)
  # Resources to create: 4 VPC endpoints, 4 Resource Configurations
  'Fn::ForEach::EndpointTypes':
    - EndpointType
    - [ssm, ssmmessages, ec2messages, sts]
    - '${EndpointType}Endpoint':
        Type: AWS::EC2::VPCEndpoint
        Properties:
          IpAddressType: 'ipv4'
          PrivateDnsEnabled: true
          SecurityGroupIds: 
            - !Ref EndpointSecurityGroup
          ServiceName: !Sub 'com.amazonaws.${AWS::Region}.${EndpointType}'
          SubnetIds:
            - !Ref EndpointsSubneta
            - !Ref EndpointsSubnetb
          VpcEndpointType: 'Interface'
          VpcId: !Ref VPC
      '${EndpointType}ResourceConfiguration':
        Type: AWS::VpcLattice::ResourceConfiguration
        Properties:
          Name: !Sub 'resource-configuration-${EndpointType}'
          CustomDomainName: !Sub '${EndpointType}.${AWS::Region}.amazonaws.com'
          PortRanges: 
            - 443
          ProtocolType: TCP
          ResourceConfigurationDefinition: 
            DnsResource:
              DomainName: !Select
                - 1
                - !Split
                  - ':'
                  - !Select
                    - 0
                    - !GetAtt
                      - !Sub '${EndpointType}Endpoint'
                      - DnsEntries
              IpAddressType: IPV4
          ResourceConfigurationType: SINGLE
          ResourceGatewayId: !Ref ResourceGateway

Outputs:
  ssmResourceConfiguration:
    Value: !GetAtt ssmResourceConfiguration.Id
  ssmmessagesResourceConfiguration:
    Value: !GetAtt ssmmessagesResourceConfiguration.Id
  ec2messagesResourceConfiguration:
    Value: !GetAtt ec2messagesResourceConfiguration.Id
  stsResourceConfiguration:
    Value: !GetAtt stsResourceConfiguration.Id