AWSTemplateFormatVersion: 2010-09-09
Description: Central AWS Networking services - VPC Lattice service network

Resources:
  # ---------- VPC LATTICE SERVICE NETWORK ----------
  VpcLatticeServiceNetwork:
    Type: AWS::VpcLattice::ServiceNetwork
    Properties:
      AuthType: NONE
      Name: service-network
  
  VpcLatticeServiceAssociation:
    Type: AWS::VpcLattice::ServiceNetworkServiceAssociation
    Properties:
      ServiceIdentifier: !GetAtt GetRAMResourceShare.VpcLatticeService
      ServiceNetworkIdentifier: !Ref VpcLatticeServiceNetwork
  
  # ---------- RAM SHARE VPC LATTICE SERVICE NETWORK (AWS ORGANIZATION) ---------
  RAMShare:
    Type: AWS::RAM::ResourceShare
    Properties:
      AllowExternalPrincipals: false
      Name: service-network-resource-share
      Principals: 
        - !GetAtt GetOrganizationId.OrganizationArn
      ResourceArns: 
        - !GetAtt VpcLatticeServiceNetwork.Arn

  # ---------- CUSTOM RESOURCE: GET ORGANIZATION ID ----------
  GetOrganizationId:
    Type: Custom::GetOrganizationId
    Properties:
      ServiceToken: !GetAtt GetOrgIdFunction.Arn

  GetOrgIdFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub get-org-id-${AWS::StackName}
      Runtime: python3.14
      Handler: index.handler
      Role: !GetAtt GetOrgIdRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          
          def handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  org_client = boto3.client('organizations')
                  response = org_client.describe_organization()
                  org_id = response['Organization']['Id']
                  org_arn = response['Organization']['Arn']
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                      'OrganizationId': org_id,
                      'OrganizationArn': org_arn
                  })
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})

  GetOrgIdRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: OrganizationsReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - organizations:DescribeOrganization
                Resource: '*'

  # ---------- CUSTOM RESOURCE: GET RAM RESOURCE SHARE ----------
  GetRAMResourceShare:
    Type: Custom::GetRAMResourceShare
    Properties:
      ServiceToken: !GetAtt GetRAMShareFunction.Arn
      ShareName: service-resource-share

  GetRAMShareFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub get-ram-share-${AWS::StackName}
      Runtime: python3.14
      Handler: index.handler
      Role: !GetAtt GetRAMShareRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          
          def handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return
                  
                  share_name = event['ResourceProperties']['ShareName']
                  ram_client = boto3.client('ram')
                  
                  # Get resource shares shared WITH this account
                  response = ram_client.get_resource_shares(
                      resourceOwner='OTHER-ACCOUNTS',
                      name=share_name
                  )
                  
                  if not response['resourceShares']:
                      cfnresponse.send(event, context, cfnresponse.FAILED, 
                                     {'Error': f'No resource share found with name: {share_name}'})
                      return
                  
                  share = response['resourceShares'][0]
                  
                  # Get associated resources
                  resources_response = ram_client.list_resources(
                      resourceOwner='OTHER-ACCOUNTS',
                      resourceShareArns=[share['resourceShareArn']]
                  )
                  
                  resource_arns = [r['arn'] for r in resources_response.get('resources', [])]
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                      'ResourceShareArn': share['resourceShareArn'],
                      'ResourceShareName': share['name'],
                      'Status': share['status'],
                      'OwningAccountId': share['owningAccountId'],
                      'ResourceArns': ','.join(resource_arns),
                      'VpcLatticeService': resource_arns[0] if resource_arns else ''
                  })
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  GetRAMShareRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RAMReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ram:GetResourceShares
                  - ram:ListResources
                Resource: '*'
