AWSTemplateFormatVersion: 2010-09-09
Description: Central AWS Networking services - VPC Lattice service network

Resources:
  VpcLatticeServiceNetwork:
    Type: AWS::VpcLattice::ServiceNetwork
    Properties:
      AuthType: NONE
      Name: service-network

Outputs:
  VpcLatticeServiceNetworkId:
    Value: !Ref VpcLatticeServiceNetwork
    Description: VPC Lattice service network ID